// Auto-generated by Supabase MCP — do not edit by hand.
// Regenerate: pnpm types:supabase (uses MCP).
// Schemas: public, ads (and others present in DB).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      ai_accuracy_logs: {
        Row: {
          accuracy_pct: number | null
          confusion_matrix: Json | null
          correct_count: number
          created_at: string
          id: string
          period_end: string
          period_start: string
          prompt_type: string
          prompt_version: number
          top_errors: Json | null
          total_analyzed: number
          total_confirmed: number
          wrong_count: number
        }
        Insert: {
          accuracy_pct?: number | null
          confusion_matrix?: Json | null
          correct_count?: number
          created_at?: string
          id?: string
          period_end: string
          period_start: string
          prompt_type: string
          prompt_version: number
          top_errors?: Json | null
          total_analyzed?: number
          total_confirmed?: number
          wrong_count?: number
        }
        Update: {
          accuracy_pct?: number | null
          confusion_matrix?: Json | null
          correct_count?: number
          created_at?: string
          id?: string
          period_end?: string
          period_start?: string
          prompt_type?: string
          prompt_version?: number
          top_errors?: Json | null
          total_analyzed?: number
          total_confirmed?: number
          wrong_count?: number
        }
        Relationships: []
      }
      ai_learning_records: {
        Row: {
          created_at: string | null
          feedback: string | null
          final_draft: string | null
          id: string
          metadata: Json | null
          original_draft: string | null
          outcome: string | null
          report_id: string | null
          trigger_type: string
          violation_type: string | null
        }
        Insert: {
          created_at?: string | null
          feedback?: string | null
          final_draft?: string | null
          id?: string
          metadata?: Json | null
          original_draft?: string | null
          outcome?: string | null
          report_id?: string | null
          trigger_type: string
          violation_type?: string | null
        }
        Update: {
          created_at?: string | null
          feedback?: string | null
          final_draft?: string | null
          id?: string
          metadata?: Json | null
          original_draft?: string | null
          outcome?: string | null
          report_id?: string | null
          trigger_type?: string
          violation_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_learning_records_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_prompts: {
        Row: {
          accuracy_score: number | null
          content: string
          created_at: string
          created_by: string
          id: string
          is_active: boolean
          metadata: Json | null
          prompt_type: string
          sample_count: number | null
          version: number
        }
        Insert: {
          accuracy_score?: number | null
          content: string
          created_at?: string
          created_by: string
          id?: string
          is_active?: boolean
          metadata?: Json | null
          prompt_type: string
          sample_count?: number | null
          version?: number
        }
        Update: {
          accuracy_score?: number | null
          content?: string
          created_at?: string
          created_by?: string
          id?: string
          is_active?: boolean
          metadata?: Json | null
          prompt_type?: string
          sample_count?: number | null
          version?: number
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          action: string
          after_data: Json | null
          before_data: Json | null
          created_at: string
          details: Json | null
          id: number
          ip_address: unknown
          resource_id: string | null
          resource_type: string | null
          user_agent: string | null
          user_id: string | null
        }
        Insert: {
          action: string
          after_data?: Json | null
          before_data?: Json | null
          created_at?: string
          details?: Json | null
          id?: number
          ip_address?: unknown
          resource_id?: string | null
          resource_type?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Update: {
          action?: string
          after_data?: Json | null
          before_data?: Json | null
          created_at?: string
          details?: Json | null
          id?: number
          ip_address?: unknown
          resource_id?: string | null
          resource_type?: string | null
          user_agent?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      br_case_events: {
        Row: {
          actor_id: string | null
          created_at: string | null
          event_type: string
          id: string
          metadata: Json | null
          new_value: string | null
          old_value: string | null
          report_id: string
        }
        Insert: {
          actor_id?: string | null
          created_at?: string | null
          event_type: string
          id?: string
          metadata?: Json | null
          new_value?: string | null
          old_value?: string | null
          report_id: string
        }
        Update: {
          actor_id?: string | null
          created_at?: string | null
          event_type?: string
          id?: string
          metadata?: Json | null
          new_value?: string | null
          old_value?: string | null
          report_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "br_case_events_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      br_case_messages: {
        Row: {
          attachments: Json | null
          body: string
          br_case_id: string
          created_at: string | null
          direction: string
          id: string
          report_id: string
          scraped_at: string | null
          sender: string
          sent_at: string
        }
        Insert: {
          attachments?: Json | null
          body: string
          br_case_id: string
          created_at?: string | null
          direction: string
          id?: string
          report_id: string
          scraped_at?: string | null
          sender: string
          sent_at: string
        }
        Update: {
          attachments?: Json | null
          body?: string
          br_case_id?: string
          created_at?: string | null
          direction?: string
          id?: string
          report_id?: string
          scraped_at?: string | null
          sender?: string
          sent_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "br_case_messages_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      br_case_notes: {
        Row: {
          body: string
          created_at: string | null
          id: string
          report_id: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          body: string
          created_at?: string | null
          id?: string
          report_id: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          body?: string
          created_at?: string | null
          id?: string
          report_id?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "br_case_notes_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      br_templates: {
        Row: {
          active: boolean | null
          body: string
          br_form_type: string
          category: string
          code: string
          created_at: string | null
          id: string
          instruction: string | null
          placeholders: string[] | null
          subject: string | null
          title: string
          updated_at: string | null
          violation_codes: string[] | null
        }
        Insert: {
          active?: boolean | null
          body: string
          br_form_type: string
          category: string
          code: string
          created_at?: string | null
          id?: string
          instruction?: string | null
          placeholders?: string[] | null
          subject?: string | null
          title: string
          updated_at?: string | null
          violation_codes?: string[] | null
        }
        Update: {
          active?: boolean | null
          body?: string
          br_form_type?: string
          category?: string
          code?: string
          created_at?: string | null
          id?: string
          instruction?: string | null
          placeholders?: string[] | null
          subject?: string | null
          title?: string
          updated_at?: string | null
          violation_codes?: string[] | null
        }
        Relationships: []
      }
      brand_market_permissions: {
        Row: {
          brand_market_id: string
          created_at: string | null
          id: string
          org_unit_id: string
          permission: string
        }
        Insert: {
          brand_market_id: string
          created_at?: string | null
          id?: string
          org_unit_id: string
          permission?: string
        }
        Update: {
          brand_market_id?: string
          created_at?: string | null
          id?: string
          org_unit_id?: string
          permission?: string
        }
        Relationships: [
          {
            foreignKeyName: "brand_market_permissions_brand_market_id_fkey"
            columns: ["brand_market_id"]
            isOneToOne: false
            referencedRelation: "brand_markets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "brand_market_permissions_org_unit_id_fkey"
            columns: ["org_unit_id"]
            isOneToOne: false
            referencedRelation: "org_units"
            referencedColumns: ["id"]
          },
        ]
      }
      brand_markets: {
        Row: {
          account_name: string | null
          brand_id: string
          created_at: string | null
          id: string
          is_active: boolean | null
          marketplace: string
        }
        Insert: {
          account_name?: string | null
          brand_id: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          marketplace: string
        }
        Update: {
          account_name?: string | null
          brand_id?: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          marketplace?: string
        }
        Relationships: [
          {
            foreignKeyName: "brand_markets_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
        ]
      }
      brands: {
        Row: {
          code: string
          created_at: string | null
          description: string | null
          id: string
          is_active: boolean | null
          name: string
        }
        Insert: {
          code: string
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          name: string
        }
        Update: {
          code?: string
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
        }
        Relationships: []
      }
      campaign_listings: {
        Row: {
          campaign_id: string
          created_at: string
          listing_id: string
          page_number: number | null
          position_in_page: number | null
        }
        Insert: {
          campaign_id: string
          created_at?: string
          listing_id: string
          page_number?: number | null
          position_in_page?: number | null
        }
        Update: {
          campaign_id?: string
          created_at?: string
          listing_id?: string
          page_number?: number | null
          position_in_page?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "campaign_listings_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "campaign_listings_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      campaigns: {
        Row: {
          created_at: string
          created_by: string
          end_date: string | null
          frequency: string
          id: string
          keyword: string
          last_crawled_at: string | null
          last_result: Json | null
          marketplace: string
          max_pages: number
          start_date: string
          status: string
          success_rate: number | null
          total_listings: number | null
          total_sent: number | null
          total_violations: number | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by: string
          end_date?: string | null
          frequency?: string
          id?: string
          keyword: string
          last_crawled_at?: string | null
          last_result?: Json | null
          marketplace?: string
          max_pages?: number
          start_date: string
          status?: string
          success_rate?: number | null
          total_listings?: number | null
          total_sent?: number | null
          total_violations?: number | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          end_date?: string | null
          frequency?: string
          id?: string
          keyword?: string
          last_crawled_at?: string | null
          last_result?: Json | null
          marketplace?: string
          max_pages?: number
          start_date?: string
          status?: string
          success_rate?: number | null
          total_listings?: number | null
          total_sent?: number | null
          total_violations?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "campaigns_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      changelog_entries: {
        Row: {
          category: string
          created_at: string
          created_by: string
          description: string
          id: string
          title: string
          updated_at: string
          version: string
        }
        Insert: {
          category: string
          created_at?: string
          created_by: string
          description: string
          id?: string
          title: string
          updated_at?: string
          version: string
        }
        Update: {
          category?: string
          created_at?: string
          created_by?: string
          description?: string
          id?: string
          title?: string
          updated_at?: string
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "changelog_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      crawler_logs: {
        Row: {
          asin: string | null
          campaign_id: string | null
          captchas: number | null
          created_at: string
          duplicates: number | null
          duration_ms: number | null
          error_code: string | null
          errors: number | null
          id: string
          keyword: string | null
          listings_found: number | null
          listings_sent: number | null
          marketplace: string | null
          message: string | null
          new_listings: number | null
          pages_crawled: number | null
          proxy_rotations: number | null
          type: string
        }
        Insert: {
          asin?: string | null
          campaign_id?: string | null
          captchas?: number | null
          created_at?: string
          duplicates?: number | null
          duration_ms?: number | null
          error_code?: string | null
          errors?: number | null
          id?: string
          keyword?: string | null
          listings_found?: number | null
          listings_sent?: number | null
          marketplace?: string | null
          message?: string | null
          new_listings?: number | null
          pages_crawled?: number | null
          proxy_rotations?: number | null
          type: string
        }
        Update: {
          asin?: string | null
          campaign_id?: string | null
          captchas?: number | null
          created_at?: string
          duplicates?: number | null
          duration_ms?: number | null
          error_code?: string | null
          errors?: number | null
          id?: string
          keyword?: string | null
          listings_found?: number | null
          listings_sent?: number | null
          marketplace?: string | null
          message?: string | null
          new_listings?: number | null
          pages_crawled?: number | null
          proxy_rotations?: number | null
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "crawler_logs_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      extension_fetch_queue: {
        Row: {
          asin: string
          completed_at: string | null
          created_at: string | null
          error: string | null
          id: string
          marketplace: string
          metadata: Json | null
          picked_up_at: string | null
          picked_up_by: string | null
          requested_by: string | null
          result: Json | null
          status: string
        }
        Insert: {
          asin: string
          completed_at?: string | null
          created_at?: string | null
          error?: string | null
          id?: string
          marketplace?: string
          metadata?: Json | null
          picked_up_at?: string | null
          picked_up_by?: string | null
          requested_by?: string | null
          result?: Json | null
          status?: string
        }
        Update: {
          asin?: string
          completed_at?: string | null
          created_at?: string | null
          error?: string | null
          id?: string
          marketplace?: string
          metadata?: Json | null
          picked_up_at?: string | null
          picked_up_by?: string | null
          requested_by?: string | null
          result?: Json | null
          status?: string
        }
        Relationships: []
      }
      extension_releases: {
        Row: {
          changes: string[]
          created_at: string
          download_url: string
          id: string
          released_at: string
          version: string
        }
        Insert: {
          changes?: string[]
          created_at?: string
          download_url: string
          id?: string
          released_at?: string
          version: string
        }
        Update: {
          changes?: string[]
          created_at?: string
          download_url?: string
          id?: string
          released_at?: string
          version?: string
        }
        Relationships: []
      }
      ip_assets: {
        Row: {
          application_date: string | null
          application_number: string | null
          assignee: string | null
          country: string
          created_at: string
          description: string | null
          expiry_date: string | null
          id: string
          image_urls: string[] | null
          ip_type: string
          keywords: string[] | null
          management_number: string
          monday_board_id: string | null
          monday_item_id: string | null
          name: string
          notes: string | null
          registration_date: string | null
          registration_number: string | null
          related_products: string[] | null
          report_url: string | null
          status: string
          synced_at: string | null
          updated_at: string
        }
        Insert: {
          application_date?: string | null
          application_number?: string | null
          assignee?: string | null
          country?: string
          created_at?: string
          description?: string | null
          expiry_date?: string | null
          id?: string
          image_urls?: string[] | null
          ip_type: string
          keywords?: string[] | null
          management_number: string
          monday_board_id?: string | null
          monday_item_id?: string | null
          name: string
          notes?: string | null
          registration_date?: string | null
          registration_number?: string | null
          related_products?: string[] | null
          report_url?: string | null
          status?: string
          synced_at?: string | null
          updated_at?: string
        }
        Update: {
          application_date?: string | null
          application_number?: string | null
          assignee?: string | null
          country?: string
          created_at?: string
          description?: string | null
          expiry_date?: string | null
          id?: string
          image_urls?: string[] | null
          ip_type?: string
          keywords?: string[] | null
          management_number?: string
          monday_board_id?: string | null
          monday_item_id?: string | null
          name?: string
          notes?: string | null
          registration_date?: string | null
          registration_number?: string | null
          related_products?: string[] | null
          report_url?: string | null
          status?: string
          synced_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      listings: {
        Row: {
          asin: string
          brand: string | null
          bullet_points: Json | null
          category: string | null
          crawled_at: string
          crawler_ai_result: Json | null
          created_at: string
          description: string | null
          fetch_error: string | null
          fetch_status: string | null
          id: string
          images: Json | null
          is_suspect: boolean
          last_fetched_at: string | null
          marketplace: string
          price_amount: number | null
          price_currency: string | null
          rating: number | null
          raw_data: Json | null
          review_count: number | null
          screenshot_url: string | null
          seller_id: string | null
          seller_name: string | null
          source: string
          source_campaign_id: string | null
          source_user_id: string | null
          suspect_reasons: Json | null
          title: string | null
          updated_at: string
        }
        Insert: {
          asin: string
          brand?: string | null
          bullet_points?: Json | null
          category?: string | null
          crawled_at?: string
          crawler_ai_result?: Json | null
          created_at?: string
          description?: string | null
          fetch_error?: string | null
          fetch_status?: string | null
          id?: string
          images?: Json | null
          is_suspect?: boolean
          last_fetched_at?: string | null
          marketplace: string
          price_amount?: number | null
          price_currency?: string | null
          rating?: number | null
          raw_data?: Json | null
          review_count?: number | null
          screenshot_url?: string | null
          seller_id?: string | null
          seller_name?: string | null
          source: string
          source_campaign_id?: string | null
          source_user_id?: string | null
          suspect_reasons?: Json | null
          title?: string | null
          updated_at?: string
        }
        Update: {
          asin?: string
          brand?: string | null
          bullet_points?: Json | null
          category?: string | null
          crawled_at?: string
          crawler_ai_result?: Json | null
          created_at?: string
          description?: string | null
          fetch_error?: string | null
          fetch_status?: string | null
          id?: string
          images?: Json | null
          is_suspect?: boolean
          last_fetched_at?: string | null
          marketplace?: string
          price_amount?: number | null
          price_currency?: string | null
          rating?: number | null
          raw_data?: Json | null
          review_count?: number | null
          screenshot_url?: string | null
          seller_id?: string | null
          seller_name?: string | null
          source?: string
          source_campaign_id?: string | null
          source_user_id?: string | null
          suspect_reasons?: Json | null
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "listings_source_campaign_id_fkey"
            columns: ["source_campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_source_user_id_fkey"
            columns: ["source_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      module_access_configs: {
        Row: {
          access_level: string
          description: string | null
          id: string
          module_key: string
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          access_level?: string
          description?: string | null
          id?: string
          module_key: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          access_level?: string
          description?: string | null
          id?: string
          module_key?: string
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "module_access_configs_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notice_reads: {
        Row: {
          id: string
          notice_id: string
          read_at: string
          user_id: string
        }
        Insert: {
          id?: string
          notice_id: string
          read_at?: string
          user_id: string
        }
        Update: {
          id?: string
          notice_id?: string
          read_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notice_reads_notice_id_fkey"
            columns: ["notice_id"]
            isOneToOne: false
            referencedRelation: "notices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notice_reads_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notices: {
        Row: {
          category: string
          content: string
          created_at: string
          created_by: string | null
          id: string
          is_pinned: boolean
          title: string
          updated_at: string
        }
        Insert: {
          category?: string
          content: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_pinned?: boolean
          title: string
          updated_at?: string
        }
        Update: {
          category?: string
          content?: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_pinned?: boolean
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notices_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_rules: {
        Row: {
          channel: string
          condition: Json | null
          created_at: string | null
          enabled: boolean | null
          id: string
          target_role: string
          trigger_type: string
        }
        Insert: {
          channel?: string
          condition?: Json | null
          created_at?: string | null
          enabled?: boolean | null
          id?: string
          target_role: string
          trigger_type: string
        }
        Update: {
          channel?: string
          condition?: Json | null
          created_at?: string | null
          enabled?: boolean | null
          id?: string
          target_role?: string
          trigger_type?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          created_at: string
          id: string
          is_read: boolean
          message: string
          metadata: Json | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_read?: boolean
          message: string
          metadata?: Json | null
          title: string
          type: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_read?: boolean
          message?: string
          metadata?: Json | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      org_units: {
        Row: {
          created_at: string | null
          id: string
          is_active: boolean | null
          level: string
          name: string
          parent_id: string | null
          sort_order: number | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          level: string
          name: string
          parent_id?: string | null
          sort_order?: number | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          level?: string
          name?: string
          parent_id?: string | null
          sort_order?: number | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "org_units_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "org_units"
            referencedColumns: ["id"]
          },
        ]
      }
      patents: {
        Row: {
          country: string
          created_at: string
          expiry_date: string | null
          id: string
          image_urls: Json | null
          keywords: Json | null
          monday_item_id: string | null
          patent_name: string
          patent_number: string
          status: string
          synced_at: string | null
          updated_at: string
        }
        Insert: {
          country?: string
          created_at?: string
          expiry_date?: string | null
          id?: string
          image_urls?: Json | null
          keywords?: Json | null
          monday_item_id?: string | null
          patent_name: string
          patent_number: string
          status?: string
          synced_at?: string | null
          updated_at?: string
        }
        Update: {
          country?: string
          created_at?: string
          expiry_date?: string | null
          id?: string
          image_urls?: Json | null
          keywords?: Json | null
          monday_item_id?: string | null
          patent_name?: string
          patent_number?: string
          status?: string
          synced_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      product_categories: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          name: string
          slug: string
          sort_order: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name: string
          slug: string
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          name?: string
          slug?: string
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_categories_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      report_patents: {
        Row: {
          ai_reasoning: string | null
          created_at: string
          patent_id: string
          report_id: string
          similarity_score: number | null
        }
        Insert: {
          ai_reasoning?: string | null
          created_at?: string
          patent_id: string
          report_id: string
          similarity_score?: number | null
        }
        Update: {
          ai_reasoning?: string | null
          created_at?: string
          patent_id?: string
          report_id?: string
          similarity_score?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "report_patents_patent_id_fkey"
            columns: ["patent_id"]
            isOneToOne: false
            referencedRelation: "patents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "report_patents_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      report_read_status: {
        Row: {
          read_at: string
          report_id: string
          user_id: string
        }
        Insert: {
          read_at?: string
          report_id: string
          user_id: string
        }
        Update: {
          read_at?: string
          report_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "report_read_status_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "report_read_status_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      report_snapshots: {
        Row: {
          change_detected: boolean | null
          change_type: string | null
          crawled_at: string
          created_at: string
          diff_from_initial: Json | null
          id: string
          listing_data: Json
          report_id: string
          snapshot_type: string
        }
        Insert: {
          change_detected?: boolean | null
          change_type?: string | null
          crawled_at?: string
          created_at?: string
          diff_from_initial?: Json | null
          id?: string
          listing_data: Json
          report_id: string
          snapshot_type: string
        }
        Update: {
          change_detected?: boolean | null
          change_type?: string | null
          crawled_at?: string
          created_at?: string
          diff_from_initial?: Json | null
          id?: string
          listing_data?: Json
          report_id?: string
          snapshot_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "report_snapshots_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      report_templates: {
        Row: {
          body: string
          category: string | null
          created_at: string | null
          created_by: string | null
          id: string
          is_default: boolean | null
          marketplace: string[] | null
          tags: string[] | null
          title: string
          updated_at: string | null
          usage_count: number | null
          violation_types: string[] | null
        }
        Insert: {
          body: string
          category?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          is_default?: boolean | null
          marketplace?: string[] | null
          tags?: string[] | null
          title: string
          updated_at?: string | null
          usage_count?: number | null
          violation_types?: string[] | null
        }
        Update: {
          body?: string
          category?: string | null
          created_at?: string | null
          created_by?: string | null
          id?: string
          is_default?: boolean | null
          marketplace?: string[] | null
          tags?: string[] | null
          title?: string
          updated_at?: string | null
          usage_count?: number | null
          violation_types?: string[] | null
        }
        Relationships: [
          {
            foreignKeyName: "report_templates_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          admin_memo: string | null
          ai_analysis: Json | null
          ai_confidence_score: number | null
          ai_severity: string | null
          ai_tone_suggestion: Json | null
          ai_violation_type: string | null
          approved_at: string | null
          approved_by: string | null
          archive_reason: string | null
          archived_at: string | null
          br_case_id: string | null
          br_case_id_retry_count: number | null
          br_case_status: string | null
          br_form_type: string | null
          br_last_amazon_reply_at: string | null
          br_last_our_reply_at: string | null
          br_last_scraped_at: string | null
          br_reply_classification: string | null
          br_reply_pending_attachments: Json | null
          br_reply_pending_text: string | null
          br_reply_read_at: string | null
          br_submission_error: string | null
          br_submit_attempts: number | null
          br_submit_data: Json | null
          br_submitted_at: string | null
          cancellation_reason: string | null
          cancelled_at: string | null
          cancelled_by: string | null
          confirmed_violation_type: string | null
          created_at: string
          created_by: string
          disagreement_flag: boolean | null
          draft_body: string | null
          draft_evidence: Json | null
          draft_policy_references: Json | null
          draft_subject: string | null
          draft_title: string | null
          edited_at: string | null
          edited_by: string | null
          escalation_level: number | null
          id: string
          last_resubmit_at: string | null
          listing_id: string | null
          listing_snapshot: Json | null
          max_resubmit_count: number | null
          monitoring_started_at: string | null
          next_resubmit_at: string | null
          note: string | null
          original_draft_body: string | null
          parent_report_id: string | null
          pd_case_id: string | null
          pd_followup_interval_days: number | null
          pd_last_attempt_at: string | null
          pd_submission_error: string | null
          pd_submit_attempts: number | null
          pd_submit_data: Json | null
          pd_submitted_at: string | null
          pre_archive_status: string | null
          rejected_at: string | null
          rejected_by: string | null
          rejection_category: string | null
          rejection_reason: string | null
          related_asins: Json
          report_number: number
          resolution_type: string | null
          resolved_at: string | null
          resubmit_count: number | null
          resubmit_interval_days: number | null
          screenshot_url: string | null
          screenshot_urls: Json | null
          screenshots: Json | null
          source: string | null
          status: string
          updated_at: string
          user_violation_type: string | null
          violation_category: string | null
          violation_type: string | null
        }
        Insert: {
          admin_memo?: string | null
          ai_analysis?: Json | null
          ai_confidence_score?: number | null
          ai_severity?: string | null
          ai_tone_suggestion?: Json | null
          ai_violation_type?: string | null
          approved_at?: string | null
          approved_by?: string | null
          archive_reason?: string | null
          archived_at?: string | null
          br_case_id?: string | null
          br_case_id_retry_count?: number | null
          br_case_status?: string | null
          br_form_type?: string | null
          br_last_amazon_reply_at?: string | null
          br_last_our_reply_at?: string | null
          br_last_scraped_at?: string | null
          br_reply_classification?: string | null
          br_reply_pending_attachments?: Json | null
          br_reply_pending_text?: string | null
          br_reply_read_at?: string | null
          br_submission_error?: string | null
          br_submit_attempts?: number | null
          br_submit_data?: Json | null
          br_submitted_at?: string | null
          cancellation_reason?: string | null
          cancelled_at?: string | null
          cancelled_by?: string | null
          confirmed_violation_type?: string | null
          created_at?: string
          created_by: string
          disagreement_flag?: boolean | null
          draft_body?: string | null
          draft_evidence?: Json | null
          draft_policy_references?: Json | null
          draft_subject?: string | null
          draft_title?: string | null
          edited_at?: string | null
          edited_by?: string | null
          escalation_level?: number | null
          id?: string
          last_resubmit_at?: string | null
          listing_id?: string | null
          listing_snapshot?: Json | null
          max_resubmit_count?: number | null
          monitoring_started_at?: string | null
          next_resubmit_at?: string | null
          note?: string | null
          original_draft_body?: string | null
          parent_report_id?: string | null
          pd_case_id?: string | null
          pd_followup_interval_days?: number | null
          pd_last_attempt_at?: string | null
          pd_submission_error?: string | null
          pd_submit_attempts?: number | null
          pd_submit_data?: Json | null
          pd_submitted_at?: string | null
          pre_archive_status?: string | null
          rejected_at?: string | null
          rejected_by?: string | null
          rejection_category?: string | null
          rejection_reason?: string | null
          related_asins?: Json
          report_number?: number
          resolution_type?: string | null
          resolved_at?: string | null
          resubmit_count?: number | null
          resubmit_interval_days?: number | null
          screenshot_url?: string | null
          screenshot_urls?: Json | null
          screenshots?: Json | null
          source?: string | null
          status?: string
          updated_at?: string
          user_violation_type?: string | null
          violation_category?: string | null
          violation_type?: string | null
        }
        Update: {
          admin_memo?: string | null
          ai_analysis?: Json | null
          ai_confidence_score?: number | null
          ai_severity?: string | null
          ai_tone_suggestion?: Json | null
          ai_violation_type?: string | null
          approved_at?: string | null
          approved_by?: string | null
          archive_reason?: string | null
          archived_at?: string | null
          br_case_id?: string | null
          br_case_id_retry_count?: number | null
          br_case_status?: string | null
          br_form_type?: string | null
          br_last_amazon_reply_at?: string | null
          br_last_our_reply_at?: string | null
          br_last_scraped_at?: string | null
          br_reply_classification?: string | null
          br_reply_pending_attachments?: Json | null
          br_reply_pending_text?: string | null
          br_reply_read_at?: string | null
          br_submission_error?: string | null
          br_submit_attempts?: number | null
          br_submit_data?: Json | null
          br_submitted_at?: string | null
          cancellation_reason?: string | null
          cancelled_at?: string | null
          cancelled_by?: string | null
          confirmed_violation_type?: string | null
          created_at?: string
          created_by?: string
          disagreement_flag?: boolean | null
          draft_body?: string | null
          draft_evidence?: Json | null
          draft_policy_references?: Json | null
          draft_subject?: string | null
          draft_title?: string | null
          edited_at?: string | null
          edited_by?: string | null
          escalation_level?: number | null
          id?: string
          last_resubmit_at?: string | null
          listing_id?: string | null
          listing_snapshot?: Json | null
          max_resubmit_count?: number | null
          monitoring_started_at?: string | null
          next_resubmit_at?: string | null
          note?: string | null
          original_draft_body?: string | null
          parent_report_id?: string | null
          pd_case_id?: string | null
          pd_followup_interval_days?: number | null
          pd_last_attempt_at?: string | null
          pd_submission_error?: string | null
          pd_submit_attempts?: number | null
          pd_submit_data?: Json | null
          pd_submitted_at?: string | null
          pre_archive_status?: string | null
          rejected_at?: string | null
          rejected_by?: string | null
          rejection_category?: string | null
          rejection_reason?: string | null
          related_asins?: Json
          report_number?: number
          resolution_type?: string | null
          resolved_at?: string | null
          resubmit_count?: number | null
          resubmit_interval_days?: number | null
          screenshot_url?: string | null
          screenshot_urls?: Json | null
          screenshots?: Json | null
          source?: string | null
          status?: string
          updated_at?: string
          user_violation_type?: string | null
          violation_category?: string | null
          violation_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reports_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_cancelled_by_fkey"
            columns: ["cancelled_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_edited_by_fkey"
            columns: ["edited_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_parent_report_id_fkey"
            columns: ["parent_report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_rejected_by_fkey"
            columns: ["rejected_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      sc_credentials: {
        Row: {
          created_by: string
          email: string
          id: string
          last_used_at: string | null
          marketplace: string
          mfa_vault_secret_id: string | null
          updated_at: string
          vault_secret_id: string
        }
        Insert: {
          created_by: string
          email: string
          id?: string
          last_used_at?: string | null
          marketplace: string
          mfa_vault_secret_id?: string | null
          updated_at?: string
          vault_secret_id: string
        }
        Update: {
          created_by?: string
          email?: string
          id?: string
          last_used_at?: string | null
          marketplace?: string
          mfa_vault_secret_id?: string | null
          updated_at?: string
          vault_secret_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sc_credentials_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      system_configs: {
        Row: {
          description: string | null
          key: string
          updated_at: string
          updated_by: string | null
          value: Json
        }
        Insert: {
          description?: string | null
          key: string
          updated_at?: string
          updated_by?: string | null
          value: Json
        }
        Update: {
          description?: string | null
          key?: string
          updated_at?: string
          updated_by?: string | null
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "system_configs_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      trademarks: {
        Row: {
          country: string
          created_at: string
          id: string
          image_url: string | null
          is_active: boolean
          mark_type: string
          name: string
          registration_number: string | null
          updated_at: string
          variations: Json | null
        }
        Insert: {
          country?: string
          created_at?: string
          id?: string
          image_url?: string | null
          is_active?: boolean
          mark_type: string
          name: string
          registration_number?: string | null
          updated_at?: string
          variations?: Json | null
        }
        Update: {
          country?: string
          created_at?: string
          id?: string
          image_url?: string | null
          is_active?: boolean
          mark_type?: string
          name?: string
          registration_number?: string | null
          updated_at?: string
          variations?: Json | null
        }
        Relationships: []
      }
      user_org_units: {
        Row: {
          created_at: string | null
          id: string
          is_primary: boolean | null
          org_unit_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          is_primary?: boolean | null
          org_unit_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          is_primary?: boolean | null
          org_unit_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_org_units_org_unit_id_fkey"
            columns: ["org_unit_id"]
            isOneToOne: false
            referencedRelation: "org_units"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_org_units_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      user_preferences: {
        Row: {
          created_at: string
          id: string
          preference_key: string
          preference_value: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          preference_key: string
          preference_value: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          preference_key?: string
          preference_value?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          id: string
          is_active: boolean
          last_login_at: string | null
          name: string
          role: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          name: string
          role?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          id?: string
          is_active?: boolean
          last_login_at?: string | null
          name?: string
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      count_listings_by_campaigns: {
        Args: { campaign_ids: string[] }
        Returns: {
          cnt: number
          source_campaign_id: string
        }[]
      }
      delete_campaign_cascade: {
        Args: { p_campaign_id: string }
        Returns: undefined
      }
      get_accessible_brand_markets: {
        Args: { p_module_key: string; p_user_id: string }
        Returns: string[]
      }
      get_accessible_org_units: {
        Args: { p_module_key: string; p_user_id: string }
        Returns: string[]
      }
      get_brand_market_permission: {
        Args: {
          p_brand_market_id: string
          p_module_key: string
          p_user_id: string
        }
        Returns: string
      }
      get_editable_brand_markets: {
        Args: { p_module_key: string; p_user_id: string }
        Returns: string[]
      }
      get_unread_notices: {
        Args: { p_user_id: string }
        Returns: {
          category: string
          content: string
          created_at: string
          created_by: string | null
          id: string
          is_pinned: boolean
          title: string
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "notices"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      increment_template_usage: {
        Args: { p_template_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
