import type { TimelineEvent } from '@/types/reports'

// Demo mock data for testing UI without Supabase

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@spigen.com',
  name: 'Demo Admin',
  role: 'admin' as const,
  avatar_url: null,
  is_active: true,
  created_at: '2026-01-01T00:00:00.000Z',
  updated_at: '2026-01-01T00:00:00.000Z',
}

export const DEMO_CAMPAIGNS = [
  {
    id: 'camp-001',
    keyword: 'spigen iphone 16 case',
    marketplace: 'US',
    status: 'active',
    frequency: 'daily',
    max_pages: 5,
    start_date: '2026-02-01',
    end_date: null,
    created_by: 'demo-user-001',
    created_at: '2026-02-01T09:00:00.000Z',
    updated_at: '2026-02-28T12:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'camp-002',
    keyword: 'spigen galaxy s25 ultra',
    marketplace: 'US',
    status: 'active',
    frequency: 'weekly',
    max_pages: 3,
    start_date: '2026-02-10',
    end_date: '2026-06-30',
    created_by: 'demo-user-001',
    created_at: '2026-02-10T10:00:00.000Z',
    updated_at: '2026-02-28T12:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'camp-003',
    keyword: 'spigen magsafe charger',
    marketplace: 'JP',
    status: 'paused',
    frequency: 'daily',
    max_pages: 3,
    start_date: '2026-01-15',
    end_date: null,
    created_by: 'demo-user-001',
    created_at: '2026-01-15T08:00:00.000Z',
    updated_at: '2026-02-20T15:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'camp-004',
    keyword: 'spigen apple watch band',
    marketplace: 'UK',
    status: 'completed',
    frequency: 'weekly',
    max_pages: 2,
    start_date: '2026-01-01',
    end_date: '2026-02-15',
    created_by: 'demo-user-001',
    created_at: '2026-01-01T07:00:00.000Z',
    updated_at: '2026-02-15T23:59:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
]

export const DEMO_LISTINGS = [
  {
    id: 'list-001',
    asin: 'B0D1234567',
    marketplace: 'US',
    title: 'Premium iPhone 16 Pro Max Case - Spigen Compatible Clear Design Ultra Slim',
    description: 'High quality case compatible with iPhone 16 Pro Max...',
    bullet_points: ['Crystal clear design', 'MagSafe compatible', 'Military grade protection'],
    price_amount: 12.99,
    price_currency: 'USD',
    seller_name: 'TechCase Store',
    seller_id: 'A3EXAMPLE',
    brand: 'GenericBrand',
    rating: 4.2,
    review_count: 847,
    source: 'crawler',
    is_suspect: true,
    suspect_reasons: ['trademark_in_title', 'price_undercut', 'review_spike'],
    crawled_at: '2026-02-28T10:00:00.000Z',
    created_at: '2026-02-28T10:00:00.000Z',
  },
  {
    id: 'list-002',
    asin: 'B0D2345678',
    marketplace: 'US',
    title: 'Galaxy S25 Ultra Tough Armor Case Military Grade Protection MagSafe',
    description: 'Designed for Samsung Galaxy S25 Ultra. Features our signature Tough Armor technology...',
    bullet_points: ['Tough Armor design', 'Raised bezels', 'Tactile buttons'],
    price_amount: 8.99,
    price_currency: 'USD',
    seller_name: 'PhoneAccessories HQ',
    seller_id: 'A5EXAMPLE',
    brand: 'Unknown',
    rating: 3.8,
    review_count: 2341,
    source: 'crawler',
    is_suspect: true,
    suspect_reasons: ['design_copy', 'fake_reviews'],
    crawled_at: '2026-02-28T10:30:00.000Z',
    created_at: '2026-02-28T10:30:00.000Z',
  },
  {
    id: 'list-003',
    asin: 'B0D3456789',
    marketplace: 'US',
    title: 'Clear Case for iPhone 16 - Slim Fit Transparent Cover Anti-Yellowing',
    description: 'Simple transparent case for iPhone 16...',
    bullet_points: ['Anti-yellowing', 'Slim design', 'Wireless charging compatible'],
    price_amount: 15.99,
    price_currency: 'USD',
    seller_name: 'CaseMart Official',
    seller_id: 'A7EXAMPLE',
    brand: 'CaseMart',
    rating: 4.5,
    review_count: 156,
    source: 'crawler',
    is_suspect: false,
    suspect_reasons: [],
    crawled_at: '2026-02-28T11:00:00.000Z',
    created_at: '2026-02-28T11:00:00.000Z',
  },
  {
    id: 'list-004',
    asin: 'B0D4567890',
    marketplace: 'JP',
    title: 'Spigen風 iPhone 16 ケース クリア 耐衝撃 MagSafe対応',
    description: 'Spigenスタイルのデザインを採用した高品質ケース...',
    bullet_points: ['Spigenスタイル', 'MagSafe対応', '耐衝撃'],
    price_amount: 1280,
    price_currency: 'JPY',
    seller_name: 'JP Mobile Shop',
    seller_id: 'A9EXAMPLE',
    brand: null,
    rating: 4.0,
    review_count: 523,
    source: 'extension',
    is_suspect: true,
    suspect_reasons: ['trademark_in_title', 'counterfeit_suspected'],
    crawled_at: '2026-02-27T15:00:00.000Z',
    created_at: '2026-02-27T15:00:00.000Z',
  },
  {
    id: 'list-005',
    asin: 'B0D5678901',
    marketplace: 'US',
    title: 'MagSafe Charger Pad 15W Fast Wireless Charging Compatible with iPhone 16/15',
    description: 'Fast wireless charger with MagSafe technology...',
    bullet_points: ['15W fast charging', 'MagSafe alignment', 'LED indicator'],
    price_amount: 19.99,
    price_currency: 'USD',
    seller_name: 'ChargeTech Pro',
    seller_id: 'A2EXAMPLE',
    brand: 'ChargeTech',
    rating: 4.6,
    review_count: 89,
    source: 'crawler',
    is_suspect: false,
    suspect_reasons: [],
    crawled_at: '2026-02-26T09:00:00.000Z',
    created_at: '2026-02-26T09:00:00.000Z',
  },
]

export const DEMO_REPORTS = [
  {
    id: 'rpt-001',
    listing_id: 'list-001',
    status: 'pending_review',
    violation_type: 'V01',
    violation_category: 'intellectual_property',
    user_violation_type: 'V01',
    ai_violation_type: 'V01',
    ai_confidence_score: 92,
    confirmed_violation_type: null,
    disagreement_flag: false,
    draft_title: 'Trademark Infringement - Unauthorized use of "Spigen" in product title',
    draft_body: 'The listing B0D1234567 uses the registered trademark "Spigen" in the product title without authorization. The seller "TechCase Store" is misleading customers by implying an official Spigen product or compatibility that may not exist.\n\nEvidence:\n- Title contains "Spigen Compatible"\n- Seller is not an authorized Spigen reseller\n- Price significantly below Spigen MSRP ($12.99 vs $29.99)',
    original_draft_body: null,
    rejection_reason: null,
    rejection_category: null,
    created_by: 'demo-user-001',
    created_at: '2026-02-28T11:00:00.000Z',
    approved_at: null,
    rejected_at: null,
    sc_case_id: null,
    listings: {
      asin: 'B0D1234567',
      title: 'Premium iPhone 16 Pro Max Case - Spigen Compatible Clear Design Ultra Slim',
      marketplace: 'US',
      seller_name: 'TechCase Store',
    },
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'rpt-002',
    listing_id: 'list-002',
    status: 'draft',
    violation_type: 'V03',
    violation_category: 'intellectual_property',
    user_violation_type: 'V03',
    ai_violation_type: 'V05',
    ai_confidence_score: 67,
    confirmed_violation_type: null,
    disagreement_flag: true,
    draft_title: 'Design Patent Infringement - Tough Armor copycat',
    draft_body: 'The listing B0D2345678 copies Spigen\'s patented Tough Armor design without authorization.',
    original_draft_body: null,
    rejection_reason: null,
    rejection_category: null,
    created_by: 'demo-user-001',
    created_at: '2026-02-28T12:00:00.000Z',
    approved_at: null,
    rejected_at: null,
    sc_case_id: null,
    listings: {
      asin: 'B0D2345678',
      title: 'Galaxy S25 Ultra Tough Armor Case Military Grade Protection MagSafe',
      marketplace: 'US',
      seller_name: 'PhoneAccessories HQ',
    },
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'rpt-003',
    listing_id: 'list-004',
    status: 'approved',
    violation_type: 'V01',
    violation_category: 'intellectual_property',
    user_violation_type: 'V01',
    ai_violation_type: 'V01',
    ai_confidence_score: 98,
    confirmed_violation_type: 'V01',
    disagreement_flag: false,
    draft_title: 'Trademark Infringement - Japanese listing using Spigen brand name',
    draft_body: 'The listing B0D4567890 on Amazon JP explicitly uses "Spigen風" (Spigen-style) in the title, misleading Japanese consumers.',
    original_draft_body: null,
    rejection_reason: null,
    rejection_category: null,
    created_by: 'demo-user-001',
    created_at: '2026-02-27T16:00:00.000Z',
    approved_at: '2026-02-28T09:00:00.000Z',
    rejected_at: null,
    sc_case_id: null,
    listings: {
      asin: 'B0D4567890',
      title: 'Spigen風 iPhone 16 ケース クリア 耐衝撃 MagSafe対応',
      marketplace: 'JP',
      seller_name: 'JP Mobile Shop',
    },
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'rpt-004',
    listing_id: 'list-001',
    status: 'rejected',
    violation_type: 'V08',
    violation_category: 'listing_content',
    user_violation_type: 'V08',
    ai_violation_type: 'V06',
    ai_confidence_score: 45,
    confirmed_violation_type: null,
    disagreement_flag: true,
    draft_title: 'False Claims - Misleading product specifications',
    draft_body: 'The listing claims military grade protection but the product material is basic TPU without any certification.',
    original_draft_body: null,
    rejection_reason: 'Insufficient evidence. "Military grade" is a common marketing term and does not constitute a false claim without specific certification references.',
    rejection_category: 'insufficient_evidence',
    created_by: 'demo-user-001',
    created_at: '2026-02-25T10:00:00.000Z',
    approved_at: null,
    rejected_at: '2026-02-26T14:00:00.000Z',
    sc_case_id: null,
    listings: {
      asin: 'B0D1234567',
      title: 'Premium iPhone 16 Pro Max Case - Spigen Compatible Clear Design Ultra Slim',
      marketplace: 'US',
      seller_name: 'TechCase Store',
    },
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'rpt-007',
    listing_id: 'list-003',
    status: 'archived',
    violation_type: 'V06',
    violation_category: 'listing_content',
    user_violation_type: 'V06',
    ai_violation_type: 'V06',
    ai_confidence_score: 78,
    confirmed_violation_type: 'V06',
    disagreement_flag: false,
    draft_title: 'Misleading Product Images - Stock photos used as product images',
    draft_body: 'The listing B0D3456789 uses stock photos that do not represent the actual product being sold.',
    original_draft_body: null,
    rejection_reason: null,
    rejection_category: null,
    created_by: 'demo-user-001',
    created_at: '2026-01-15T10:00:00.000Z',
    approved_at: '2026-01-16T09:00:00.000Z',
    rejected_at: null,
    sc_case_id: 'SC-2026-001234',
    archived_at: '2026-02-28T10:00:00.000Z',
    archive_reason: 'Monitoring 60 days - no seller response, low priority',
    pre_archive_status: 'unresolved',
    listings: {
      asin: 'B0D3456789',
      title: 'Clear Case for iPhone 16 - Slim Fit Transparent Cover Anti-Yellowing',
      marketplace: 'US',
      seller_name: 'CaseMart Official',
    },
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
]

export const DEMO_AUDIT_LOGS = [
  {
    id: 'log-001',
    user_id: 'demo-user-001',
    action: 'create',
    entity_type: 'campaign',
    entity_id: 'camp-001',
    details: { keyword: 'spigen iphone 16 case', marketplace: 'US' },
    created_at: '2026-02-01T09:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'log-002',
    user_id: 'demo-user-001',
    action: 'create',
    entity_type: 'report',
    entity_id: 'rpt-001',
    details: { violation_type: 'V01', listing_asin: 'B0D1234567' },
    created_at: '2026-02-28T11:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'log-003',
    user_id: 'demo-user-001',
    action: 'approve',
    entity_type: 'report',
    entity_id: 'rpt-003',
    details: { status: 'approved' },
    created_at: '2026-02-28T09:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'log-004',
    user_id: 'demo-user-001',
    action: 'reject',
    entity_type: 'report',
    entity_id: 'rpt-004',
    details: { rejection_category: 'insufficient_evidence' },
    created_at: '2026-02-26T14:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'log-005',
    user_id: 'demo-user-001',
    action: 'update',
    entity_type: 'campaign',
    entity_id: 'camp-003',
    details: { status: 'paused' },
    created_at: '2026-02-20T15:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'log-006',
    user_id: 'demo-user-001',
    action: 'login',
    entity_type: 'user',
    entity_id: 'demo-user-001',
    details: null,
    created_at: '2026-02-28T08:00:00.000Z',
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
]

// Build demo timeline events from a demo report
export const buildDemoTimeline = (report: (typeof DEMO_REPORTS)[number]): TimelineEvent[] => {
  const events: TimelineEvent[] = []

  events.push({
    type: 'created',
    timestamp: report.created_at,
    actor: report.users.name,
    detail: null,
  })

  if (report.ai_violation_type) {
    const confidence = report.ai_confidence_score !== null ? ` (${report.ai_confidence_score}%)` : ''
    const disagreement = report.disagreement_flag
      ? ` | User: ${report.user_violation_type} \u2260 AI: ${report.ai_violation_type}`
      : ''
    events.push({
      type: 'ai_analyzed',
      timestamp: new Date(new Date(report.created_at).getTime() + 1000).toISOString(),
      actor: null,
      detail: `${report.ai_violation_type}${confidence}${disagreement}`,
    })
  }

  if (report.status !== 'draft') {
    const created = new Date(report.created_at).getTime()
    const nextTs = report.approved_at ?? report.rejected_at
    const reviewTs = nextTs
      ? new Date(Math.floor((created + new Date(nextTs).getTime()) / 2)).toISOString()
      : new Date(created + 3600000).toISOString()
    events.push({
      type: 'submitted_review',
      timestamp: reviewTs,
      actor: report.users.name,
      detail: null,
    })
  }

  if (report.approved_at) {
    events.push({
      type: 'approved',
      timestamp: report.approved_at,
      actor: 'Demo Admin',
      detail: null,
    })
  }

  if (report.rejected_at) {
    events.push({
      type: 'rejected',
      timestamp: report.rejected_at,
      actor: 'Demo Admin',
      detail: report.rejection_reason,
    })
  }

  events.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime())
  return events
}
