import type { ReportSnapshot, MonitoringSettings } from '@/types/monitoring'

export const DEMO_SNAPSHOTS: Record<string, ReportSnapshot[]> = {
  'rpt-005': [
    {
      id: 'snap-001',
      report_id: 'rpt-005',
      snapshot_type: 'initial',
      screenshot_url: null,
      listing_data: {
        title: 'Premium iPhone 16 Pro Max Case - Spigen Compatible Clear Design Ultra Slim',
        price: '$12.99',
        seller: 'TechCase Store',
        rating: '4.2',
        status: 'active',
      },
      diff_from_initial: null,
      change_detected: false,
      change_type: null,
      ai_remark: null,
      ai_marking_data: [],
      ai_resolution_suggestion: null,
      crawled_at: '2026-02-15T10:00:00Z',
      created_at: '2026-02-15T10:00:00Z',
    },
    {
      id: 'snap-002',
      report_id: 'rpt-005',
      snapshot_type: 'followup',
      screenshot_url: null,
      listing_data: {
        title: 'Premium iPhone 16 Pro Max Case - Compatible Clear Design Ultra Slim',
        price: '$12.99',
        seller: 'TechCase Store',
        rating: '4.2',
        status: 'active',
      },
      diff_from_initial: {
        title_changed: true,
        description_changed: false,
        images_changed: false,
        price_changed: false,
        seller_changed: false,
        listing_removed: false,
        changes: [
          {
            field: 'title',
            before: 'Premium iPhone 16 Pro Max Case - Spigen Compatible Clear Design Ultra Slim',
            after: 'Premium iPhone 16 Pro Max Case - Compatible Clear Design Ultra Slim',
          },
        ],
      },
      change_detected: true,
      change_type: 'content_modified',
      ai_remark: 'The infringing keyword "Spigen" has been removed from the product title. The seller appears to have modified the listing in response to the violation report. The rest of the listing content remains unchanged.',
      ai_marking_data: [
        { x: 120, y: 45, width: 300, height: 20, label: 'Title changed - "Spigen" removed', severity: 'high' },
      ],
      ai_resolution_suggestion: 'resolved',
      crawled_at: '2026-02-22T10:00:00Z',
      created_at: '2026-02-22T10:00:00Z',
    },
  ],
  'rpt-006': [
    {
      id: 'snap-003',
      report_id: 'rpt-006',
      snapshot_type: 'initial',
      screenshot_url: null,
      listing_data: {
        title: 'Galaxy S25 Ultra Tough Armor Case Military Grade',
        price: '$8.99',
        seller: 'PhoneAccessories HQ',
        rating: '3.8',
        status: 'active',
      },
      diff_from_initial: null,
      change_detected: false,
      change_type: null,
      ai_remark: null,
      ai_marking_data: [],
      ai_resolution_suggestion: null,
      crawled_at: '2026-02-10T08:00:00Z',
      created_at: '2026-02-10T08:00:00Z',
    },
    {
      id: 'snap-004',
      report_id: 'rpt-006',
      snapshot_type: 'followup',
      screenshot_url: null,
      listing_data: {
        title: 'Galaxy S25 Ultra Tough Armor Case Military Grade',
        price: '$8.99',
        seller: 'PhoneAccessories HQ',
        rating: '3.8',
        status: 'active',
      },
      diff_from_initial: {
        title_changed: false,
        description_changed: false,
        images_changed: false,
        price_changed: false,
        seller_changed: false,
        listing_removed: false,
        changes: [],
      },
      change_detected: false,
      change_type: 'no_change',
      ai_remark: 'No changes detected in the listing. The violation content remains the same as the initial snapshot. Continued monitoring recommended.',
      ai_marking_data: [],
      ai_resolution_suggestion: 'continue',
      crawled_at: '2026-02-17T08:00:00Z',
      created_at: '2026-02-17T08:00:00Z',
    },
  ],
}

export const DEMO_MONITORING_REPORTS = [
  {
    id: 'rpt-005',
    listing_id: 'list-001',
    status: 'monitoring',
    violation_type: 'V01',
    violation_category: 'intellectual_property',
    user_violation_type: 'V01',
    ai_violation_type: 'V01',
    ai_confidence_score: 92,
    confirmed_violation_type: 'V01',
    disagreement_flag: false,
    draft_title: 'Trademark Infringement - Unauthorized use of "Spigen"',
    draft_body: 'The listing B0D1234567 uses the registered trademark "Spigen" without authorization.',
    original_draft_body: null,
    rejection_reason: null,
    rejection_category: null,
    created_by: 'demo-user-001',
    created_at: '2026-02-14T11:00:00.000Z',
    approved_at: '2026-02-14T15:00:00.000Z',
    rejected_at: null,
    sc_case_id: 'SC-2026-001',
    sc_submitted_at: '2026-02-15T09:00:00.000Z',
    monitoring_started_at: '2026-02-15T10:00:00.000Z',
    resolved_at: null,
    resolution_type: null,
    listings: {
      asin: 'B0D1234567',
      title: 'Premium iPhone 16 Pro Max Case - Spigen Compatible Clear Design Ultra Slim',
      marketplace: 'US',
      seller_name: 'TechCase Store',
      brand: 'GenericBrand',
      rating: 4.2,
      review_count: 847,
      price_amount: 12.99,
      price_currency: 'USD',
    },
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
  {
    id: 'rpt-006',
    listing_id: 'list-002',
    status: 'monitoring',
    violation_type: 'V03',
    violation_category: 'intellectual_property',
    user_violation_type: 'V03',
    ai_violation_type: 'V03',
    ai_confidence_score: 88,
    confirmed_violation_type: 'V03',
    disagreement_flag: false,
    draft_title: 'Design Patent Infringement - Tough Armor copycat',
    draft_body: 'The listing B0D2345678 copies Spigen\'s Tough Armor design.',
    original_draft_body: null,
    rejection_reason: null,
    rejection_category: null,
    created_by: 'demo-user-001',
    created_at: '2026-02-09T08:00:00.000Z',
    approved_at: '2026-02-09T14:00:00.000Z',
    rejected_at: null,
    sc_case_id: 'SC-2026-002',
    sc_submitted_at: '2026-02-10T07:00:00.000Z',
    monitoring_started_at: '2026-02-10T08:00:00.000Z',
    resolved_at: null,
    resolution_type: null,
    listings: {
      asin: 'B0D2345678',
      title: 'Galaxy S25 Ultra Tough Armor Case Military Grade Protection MagSafe',
      marketplace: 'US',
      seller_name: 'PhoneAccessories HQ',
      brand: 'Unknown',
      rating: 3.8,
      review_count: 2341,
      price_amount: 8.99,
      price_currency: 'USD',
    },
    users: { name: 'Demo Admin', email: 'demo@spigen.com' },
  },
]

export const DEMO_MONITORING_SETTINGS: MonitoringSettings = {
  monitoring_interval_days: 7,
  monitoring_max_days: 90,
}

export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-001',
    user_id: 'demo-user-001',
    type: 'followup_change_detected' as const,
    title: 'Change Detected',
    message: 'Change detected in B0D1234567 - Title modified, "Spigen" keyword removed.',
    metadata: { report_id: 'rpt-005', asin: 'B0D1234567' },
    is_read: false,
    created_at: '2026-02-22T10:05:00Z',
  },
  {
    id: 'notif-002',
    user_id: 'demo-user-001',
    type: 'followup_no_change' as const,
    title: 'No Change',
    message: 'No change detected in B0D2345678 after re-visit #1.',
    metadata: { report_id: 'rpt-006', asin: 'B0D2345678' },
    is_read: true,
    created_at: '2026-02-17T08:05:00Z',
  },
]
