import type { ReportTemplate } from '@/types/templates'

// 73+ Demo templates covering V01~V19
// Based on Amazon RAV (Report a Violation) "Explain in detail" field format
// OMS 67 templates mapped + new types (V03, V09, V13~V19)

export const DEMO_TEMPLATES: ReportTemplate[] = [
  // ============================================
  // V01: Trademark Infringement (4 templates)
  // Category: intellectual_property
  // ============================================
  {
    id: 'tmpl-v01-001',
    title: 'Trademark Infringement — Logo Misuse',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing to report a trademark infringement on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis listing prominently displays the Spigen logo and registered trademarks without authorization. The seller is not an authorized distributor or licensee of Spigen Inc. The unauthorized use of our registered trademark (USPTO Registration) in the product listing title, images, and description creates consumer confusion regarding the source and quality of the product.\n\nSpecific violations observed:\n- Unauthorized use of the Spigen brand name in the product title\n- Spigen logo visible on product images without authorization\n- Brand field falsely set to "Spigen" or confusingly similar variations\n\nWe respectfully request that Amazon review this listing and take appropriate action to protect consumers and our intellectual property rights.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V01'],
    marketplace: [],
    tags: ['trademark', 'logo', 'standard'],
    is_default: true,
    usage_count: 67,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'tmpl-v01-002',
    title: 'Trademark Infringement — Name Misuse in Title',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting a trademark violation on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe seller has incorporated the "Spigen" trademark into the product title and/or bullet points to mislead consumers into believing this is a genuine Spigen product. The product is not manufactured by, affiliated with, or endorsed by Spigen Inc.\n\nThe use of our brand name in the listing title constitutes trademark infringement and violates Amazon\'s Intellectual Property Policy. This practice deceives customers who are specifically searching for authentic Spigen products.\n\nWe request immediate removal of all unauthorized references to the Spigen trademark from this listing.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V01'],
    marketplace: [],
    tags: ['trademark', 'name', 'title'],
    is_default: false,
    usage_count: 43,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v01-003',
    title: 'Trademark Infringement — Brand Confusion',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing regarding ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis listing uses a brand name that is confusingly similar to our registered trademark "Spigen." The seller\'s brand name (or product naming convention) is designed to create consumer confusion and capitalize on the goodwill associated with the Spigen brand.\n\nThe similarity in branding, combined with the product category overlap, creates a likelihood of confusion among consumers. This violates Amazon\'s Anti-Counterfeiting Policy and applicable trademark law.\n\nWe respectfully request investigation and appropriate enforcement action.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V01'],
    marketplace: [],
    tags: ['trademark', 'confusion', 'similar-name'],
    is_default: false,
    usage_count: 21,
    created_by: 'demo-admin',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'tmpl-v01-004',
    title: 'Trademark Infringement — Unauthorized Keyword Usage',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing to report unauthorized use of the "Spigen" trademark on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nWhile this product is not a Spigen product, the seller has used our trademarked brand name in the backend search keywords and/or listing content to divert traffic from legitimate Spigen listings. This constitutes keyword trademark infringement.\n\nEvidence: The listing appears in search results for "Spigen" brand queries despite having no legitimate association with our brand. Current rating: {{RATING}} with {{REVIEW_COUNT}} reviews.\n\nWe request removal of all unauthorized Spigen trademark references.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V01'],
    marketplace: [],
    tags: ['trademark', 'keyword', 'search'],
    is_default: false,
    usage_count: 15,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },

  // ============================================
  // V02: Copyright Infringement (4 templates)
  // Category: intellectual_property
  // ============================================
  {
    id: 'tmpl-v02-001',
    title: 'Copyright Infringement — Product Image Theft',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing to report copyright infringement on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe listing uses product images that are the copyrighted property of Spigen Inc. These images were created by our internal photography and design team and are protected by copyright law. The seller has copied these images without authorization and is using them to sell a product that is not manufactured by Spigen.\n\nSpecific copyrighted images used without permission:\n- Main product image matching our official product photography\n- Lifestyle images taken from our official Amazon listings\n- Infographic images with our proprietary design elements\n\nWe request immediate removal of all copyrighted images from this listing.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V02'],
    marketplace: [],
    tags: ['copyright', 'image', 'photo'],
    is_default: true,
    usage_count: 55,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-25T00:00:00Z',
  },
  {
    id: 'tmpl-v02-002',
    title: 'Copyright Infringement — Description Copy',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting a copyright violation on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe product description and bullet points contain text that has been directly copied from our official Spigen product listings. This copyrighted content was created by our marketing team and is proprietary to Spigen Inc.\n\nThe copied content includes product descriptions, feature bullet points, and technical specifications that are unique to our official listings. This unauthorized reproduction violates our copyright and misleads consumers.\n\nWe request that the copied content be removed from this listing.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V02'],
    marketplace: [],
    tags: ['copyright', 'description', 'text'],
    is_default: false,
    usage_count: 31,
    created_by: 'demo-admin',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v02-003',
    title: 'Copyright Infringement — A+ Content Copy',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing to report that ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} has copied our A+ Content (Enhanced Brand Content).\n\nSpigen\'s A+ Content includes custom-designed graphics, comparison charts, and branded modules that are copyrighted works. The seller has reproduced these materials to make their product appear as an official Spigen product.\n\nThis unauthorized reproduction of our A+ Content violates copyright law and Amazon\'s policies regarding intellectual property protection.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V02'],
    marketplace: [],
    tags: ['copyright', 'a-plus', 'ebc'],
    is_default: false,
    usage_count: 12,
    created_by: 'demo-admin',
    created_at: '2026-01-18T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'tmpl-v02-004',
    title: 'Copyright Infringement — Video Content',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} contains video content that infringes on our copyright.\n\nThe product listing features video content that was produced by Spigen Inc. for our official products. This video content is protected by copyright and has been used without authorization to promote a non-Spigen product.\n\nWe request the infringing video content be removed immediately.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V02'],
    marketplace: [],
    tags: ['copyright', 'video'],
    is_default: false,
    usage_count: 8,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-08T00:00:00Z',
  },

  // ============================================
  // V03: Patent Infringement (4 templates)
  // Category: intellectual_property
  // ============================================
  {
    id: 'tmpl-v03-001',
    title: 'Patent Infringement — Design Patent',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing to report a design patent infringement on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis product infringes on Spigen\'s registered design patents. The product\'s overall visual appearance, including its shape, configuration, and surface ornamentation, is substantially similar to our patented designs.\n\nSpigen holds multiple design patents covering the ornamental aspects of our products. The listed product copies these protected design elements, creating consumer confusion about the product\'s origin.\n\nWe request that Amazon review this listing in light of our patent rights and take appropriate action.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V03'],
    marketplace: [],
    tags: ['patent', 'design', 'utility'],
    is_default: true,
    usage_count: 28,
    created_by: 'demo-admin',
    created_at: '2026-01-14T00:00:00Z',
    updated_at: '2026-02-22T00:00:00Z',
  },
  {
    id: 'tmpl-v03-002',
    title: 'Patent Infringement — Utility Patent',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} infringes on Spigen\'s utility patent.\n\nThe product incorporates technology and functional features that are covered by our active utility patent(s). Specifically, the product\'s mechanism and functional design fall within the scope of our patent claims.\n\nWe have conducted a detailed comparison of the product against our patent claims and have determined that it practices the claimed invention without authorization.\n\nWe request Amazon take action to protect our intellectual property rights.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V03'],
    marketplace: [],
    tags: ['patent', 'utility', 'technology'],
    is_default: false,
    usage_count: 19,
    created_by: 'demo-admin',
    created_at: '2026-01-16T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v03-003',
    title: 'Patent Infringement — Trade Dress',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting trade dress infringement on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nSpigen\'s product trade dress — including the distinctive overall look and feel, packaging design, and product configuration — is well-established and recognized by consumers. The listed product copies our trade dress elements to create a misleading impression of association with Spigen.\n\nThis constitutes unfair competition and violates Amazon\'s intellectual property policies.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V03'],
    marketplace: [],
    tags: ['patent', 'trade-dress'],
    is_default: false,
    usage_count: 11,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },
  {
    id: 'tmpl-v03-004',
    title: 'Patent Infringement — Multiple Patents',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} infringes on multiple Spigen patents.\n\nOur analysis indicates this product violates both design and utility patents held by Spigen Inc. The product combines patented visual design elements with proprietary functional features covered by our utility patents.\n\nDetailed patent claim mapping is available upon request. We urge Amazon to investigate and take appropriate enforcement action.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V03'],
    marketplace: [],
    tags: ['patent', 'multiple'],
    is_default: false,
    usage_count: 6,
    created_by: 'demo-admin',
    created_at: '2026-01-25T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },

  // ============================================
  // V04: Counterfeit (3 templates)
  // Category: intellectual_property
  // ============================================
  {
    id: 'tmpl-v04-001',
    title: 'Counterfeit — Fake Spigen Product',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing to report the sale of counterfeit goods on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis product is being sold as a genuine Spigen product but is a counterfeit. We have verified that {{SELLER}} is not an authorized seller of Spigen products. The product images, while made to look identical to authentic Spigen products, show telltale signs of counterfeiting including incorrect packaging, different material quality, and missing authentic product identifiers.\n\nThe sale of counterfeit products violates Amazon\'s Anti-Counterfeiting Policy and poses potential safety risks to consumers, as counterfeit accessories have not undergone our quality testing processes.\n\nWe request immediate removal of this counterfeit listing.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V04'],
    marketplace: [],
    tags: ['counterfeit', 'fake', 'standard'],
    is_default: true,
    usage_count: 72,
    created_by: 'demo-admin',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'tmpl-v04-002',
    title: 'Counterfeit — Test Purchase Evidence',
    body: 'Dear Amazon Seller Performance Team,\n\nFollowing a test purchase of ASIN {{ASIN}} ("{{TITLE}}") from {{SELLER}} on Amazon {{MARKETPLACE}}, we have confirmed the product is counterfeit.\n\nOur quality assurance team has examined the purchased product and identified the following discrepancies from authentic Spigen products:\n- Packaging differs from genuine Spigen packaging\n- Material quality is inferior to authentic products\n- Missing authentication codes/holograms present on genuine products\n- Product weight and dimensions do not match specifications\n\nWe have photographic evidence of the counterfeit product available for review. Price: {{PRICE}}, Rating: {{RATING}} ({{REVIEW_COUNT}} reviews).\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V04'],
    marketplace: [],
    tags: ['counterfeit', 'test-purchase', 'evidence'],
    is_default: false,
    usage_count: 38,
    created_by: 'demo-admin',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-02-22T00:00:00Z',
  },
  {
    id: 'tmpl-v04-003',
    title: 'Counterfeit — Unauthorized Reseller Counterfeit',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} appears to be selling counterfeit Spigen products.\n\nThis seller is not recognized as an authorized reseller of Spigen products. Customer reviews indicate quality issues consistent with counterfeit goods, and the pricing ({{PRICE}}) is significantly below our MAP (Minimum Advertised Price), which is a strong indicator of counterfeit origin.\n\nWe request that this listing be investigated for counterfeit product violations.\n\nDate: {{TODAY}}',
    category: 'intellectual_property',
    violation_types: ['V04'],
    marketplace: [],
    tags: ['counterfeit', 'unauthorized', 'reseller'],
    is_default: false,
    usage_count: 25,
    created_by: 'demo-admin',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },

  // ============================================
  // V05: False/Exaggerated Claims (3 templates)
  // Category: listing_content
  // ============================================
  {
    id: 'tmpl-v05-001',
    title: 'False Claims — Misleading Compatibility',
    body: 'Dear Amazon Seller Performance Team,\n\nI am writing to report false advertising on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis listing makes misleading claims about product compatibility or performance that are not accurate. Specifically, the listing claims features or certifications that the product does not possess, which misleads consumers into purchasing a product based on false information.\n\nThis violates Amazon\'s Product Detail Page Rules and Consumer Protection policies regarding accurate product descriptions.\n\nWe request that the false claims be removed or the listing be taken down.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V05'],
    marketplace: [],
    tags: ['false-claims', 'misleading', 'compatibility'],
    is_default: true,
    usage_count: 22,
    created_by: 'demo-admin',
    created_at: '2026-01-14T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v05-002',
    title: 'False Claims — Exaggerated Performance',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} makes exaggerated performance claims.\n\nThe listing advertises performance characteristics (such as "military grade protection," "unbreakable," or specific test results) that are unsubstantiated and likely misleading to consumers. These claims create unfair competitive advantage through deception.\n\nAmazon\'s policies require that product claims be truthful, accurate, and substantiated.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V05'],
    marketplace: [],
    tags: ['false-claims', 'exaggerated', 'performance'],
    is_default: false,
    usage_count: 14,
    created_by: 'demo-admin',
    created_at: '2026-01-18T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'tmpl-v05-003',
    title: 'False Claims — Fake Certification',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} for displaying fake certifications.\n\nThe listing claims product certifications (MIL-STD-810G, MagSafe certified, etc.) that the product has not legitimately obtained. Displaying fake certifications is deceptive to consumers and violates Amazon policies.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V05'],
    marketplace: [],
    tags: ['false-claims', 'certification', 'fake'],
    is_default: false,
    usage_count: 9,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },

  // ============================================
  // V06: Prohibited Keywords (3 templates)
  // Category: listing_content
  // ============================================
  {
    id: 'tmpl-v06-001',
    title: 'Prohibited Keywords — Brand Name in Non-Brand Listing',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} uses prohibited brand-name keywords.\n\nThis listing includes the "Spigen" brand name in its title, bullet points, or search terms despite not being a Spigen product. This is keyword manipulation designed to divert traffic from legitimate Spigen listings and mislead consumers.\n\nAmazon\'s Search and Browse policies prohibit using other brand names as keywords to manipulate search results.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V06'],
    marketplace: [],
    tags: ['prohibited-keyword', 'brand-name', 'search'],
    is_default: true,
    usage_count: 35,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-25T00:00:00Z',
  },
  {
    id: 'tmpl-v06-002',
    title: 'Prohibited Keywords — "Compatible with" Misuse',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} for misusing the "compatible with" phrase.\n\nWhile using "compatible with [Brand]" may be acceptable in some contexts, this listing uses it in a manner that creates a false impression of endorsement or official association with Spigen. The placement and prominence of our brand name goes beyond legitimate compatibility reference.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V06'],
    marketplace: [],
    tags: ['prohibited-keyword', 'compatible', 'misuse'],
    is_default: false,
    usage_count: 18,
    created_by: 'demo-admin',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v06-003',
    title: 'Prohibited Keywords — Restricted Terms',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} uses restricted or prohibited terms.\n\nThe listing contains terms that are restricted by Amazon category guidelines, including claims about health benefits, safety certifications, or other regulated claims that require substantiation.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V06'],
    marketplace: [],
    tags: ['prohibited-keyword', 'restricted'],
    is_default: false,
    usage_count: 7,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },

  // ============================================
  // V07: Inaccurate Product Information (5 templates)
  // Category: listing_content
  // ============================================
  {
    id: 'tmpl-v07-001',
    title: 'Inaccurate Info — Wrong Product Specifications',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting inaccurate product information on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe listing contains incorrect product specifications that mislead consumers. The stated dimensions, weight, materials, or compatibility information does not match the actual product, leading to consumer dissatisfaction and returns.\n\nAccurate product information is essential for consumer trust. We request that the listing be corrected or removed.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V07'],
    marketplace: [],
    tags: ['inaccurate', 'specifications', 'wrong-info'],
    is_default: true,
    usage_count: 29,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-24T00:00:00Z',
  },
  {
    id: 'tmpl-v07-002',
    title: 'Inaccurate Info — Misleading Images',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} displays misleading product images.\n\nThe product images do not accurately represent the actual product that consumers receive. The images show features, quality, or design elements that differ from the actual product, leading to customer deception.\n\nAmazon requires product images to accurately represent the product being sold.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V07'],
    marketplace: [],
    tags: ['inaccurate', 'images', 'misleading'],
    is_default: false,
    usage_count: 20,
    created_by: 'demo-admin',
    created_at: '2026-01-13T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v07-003',
    title: 'Inaccurate Info — Wrong Category/Classification',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting that ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} is listed in the wrong product category.\n\nThe product has been intentionally placed in an incorrect category to gain visibility or avoid category-specific requirements. This miscategorization misleads consumers and violates Amazon\'s listing policies.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V07'],
    marketplace: [],
    tags: ['inaccurate', 'category', 'classification'],
    is_default: false,
    usage_count: 11,
    created_by: 'demo-admin',
    created_at: '2026-01-17T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'tmpl-v07-004',
    title: 'Inaccurate Info — Pre-announcement Product',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} appears to be a pre-announcement listing.\n\nThis listing advertises a product that has not yet been officially released or announced by the manufacturer. The product details may be speculative or based on unauthorized leaked information, which misleads consumers.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V07'],
    marketplace: [],
    tags: ['inaccurate', 'pre-announcement', 'unreleased'],
    is_default: false,
    usage_count: 8,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'tmpl-v07-005',
    title: 'Inaccurate Info — False Origin/Material Claims',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} for false origin and material claims.\n\nThe listing claims the product is made from specific premium materials or manufactured in a specific country, but evidence suggests these claims are inaccurate. This violates consumer protection standards and Amazon\'s accuracy requirements.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V07'],
    marketplace: [],
    tags: ['inaccurate', 'material', 'origin'],
    is_default: false,
    usage_count: 5,
    created_by: 'demo-admin',
    created_at: '2026-01-25T00:00:00Z',
    updated_at: '2026-02-08T00:00:00Z',
  },

  // ============================================
  // V08: Image Policy Violation (8 templates)
  // Category: listing_content
  // ============================================
  {
    id: 'tmpl-v08-001',
    title: 'Image Violation — Stolen Product Photos',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting image policy violations on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe listing uses product photographs that belong to Spigen Inc. These images were produced for our official Amazon listings and are being used without authorization. The seller is using our professional product photography to sell a competing or counterfeit product.\n\nThis violates Amazon\'s image requirements and our intellectual property rights.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'stolen', 'photo'],
    is_default: true,
    usage_count: 48,
    created_by: 'demo-admin',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'tmpl-v08-002',
    title: 'Image Violation — Logo/Watermark on Main Image',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} violates Amazon\'s main image requirements.\n\nThe main product image contains logos, watermarks, or promotional text overlays that violate Amazon\'s Product Image Requirements. Main images must be on a pure white background with no additional graphics or text.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'logo', 'watermark', 'main-image'],
    is_default: false,
    usage_count: 32,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-25T00:00:00Z',
  },
  {
    id: 'tmpl-v08-003',
    title: 'Image Violation — Non-White Background',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} has main images that do not meet Amazon\'s background requirements.\n\nThe main product image does not have a pure white (RGB 255,255,255) background as required by Amazon\'s Product Image Standards. This affects the shopping experience and violates listing policies.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'background', 'white'],
    is_default: false,
    usage_count: 24,
    created_by: 'demo-admin',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v08-004',
    title: 'Image Violation — Misleading Product Photos',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting that ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} uses misleading product images.\n\nThe product images show a different product than what is actually being sold. The images depict features, size, color, or quality that do not match the actual product received by customers.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'misleading', 'deceptive'],
    is_default: false,
    usage_count: 19,
    created_by: 'demo-admin',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v08-005',
    title: 'Image Violation — Competitor Badge/Award Misuse',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} displays unauthorized badges or award claims in product images.\n\nThe listing images include "Best Seller," "Amazon Choice," or other badges/awards that appear to be fabricated or used without authorization. This misleads consumers about the product\'s marketplace standing.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'badge', 'award'],
    is_default: false,
    usage_count: 13,
    created_by: 'demo-admin',
    created_at: '2026-01-18T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },
  {
    id: 'tmpl-v08-006',
    title: 'Image Violation — Multiple Products in Main Image',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} shows multiple products in the main image.\n\nThe main image displays accessories, bonus items, or packaging that are not included in the purchase, creating a misleading impression of what the customer will receive. Amazon requires main images to show only what the customer will receive.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'multiple-products', 'main-image'],
    is_default: false,
    usage_count: 10,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'tmpl-v08-007',
    title: 'Image Violation — Lifestyle Image as Main',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} uses a lifestyle photo as the main product image.\n\nThe main image contains a model, lifestyle scene, or props rather than showing the product on a clean white background. This violates Amazon\'s main image standards.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'lifestyle', 'main-image'],
    is_default: false,
    usage_count: 7,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-08T00:00:00Z',
  },
  {
    id: 'tmpl-v08-008',
    title: 'Image Violation — Low Resolution/Blurry',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} uses low-quality product images.\n\nThe product images are below Amazon\'s minimum resolution requirements (1000x1000 pixels) and appear blurry or pixelated. This degrades the customer experience and may indicate the seller lacks access to authentic product samples.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V08'],
    marketplace: [],
    tags: ['image', 'low-resolution', 'quality'],
    is_default: false,
    usage_count: 4,
    created_by: 'demo-admin',
    created_at: '2026-01-25T00:00:00Z',
    updated_at: '2026-02-05T00:00:00Z',
  },

  // ============================================
  // V09: Title Policy Violation (3 templates)
  // Category: listing_content
  // ============================================
  {
    id: 'tmpl-v09-001',
    title: 'Title Violation — Keyword Stuffing',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting a title policy violation on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe product title is excessively long and contains keyword stuffing, including irrelevant brand names, excessive feature descriptions, and promotional language. This violates Amazon\'s Product Title Requirements which specify titles should be clear, concise, and limited to 200 characters for most categories.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V09'],
    marketplace: [],
    tags: ['title', 'keyword-stuffing', 'length'],
    is_default: true,
    usage_count: 16,
    created_by: 'demo-admin',
    created_at: '2026-01-14T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v09-002',
    title: 'Title Violation — Promotional Text',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} contains promotional text in the title.\n\nThe title includes promotional phrases such as "Best Seller," "Hot Deal," "Free Shipping," or similar promotional language that violates Amazon\'s title formatting guidelines. Titles should describe the product, not promote sales.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V09'],
    marketplace: [],
    tags: ['title', 'promotional', 'sales-text'],
    is_default: false,
    usage_count: 10,
    created_by: 'demo-admin',
    created_at: '2026-01-18T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'tmpl-v09-003',
    title: 'Title Violation — Competing Brand Name Abuse',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} uses competing brand names in the product title.\n\nThe title includes "Spigen" or other brand names solely to divert search traffic, without the product being legitimately associated with these brands. This violates Amazon\'s Brand Name Policy.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V09'],
    marketplace: [],
    tags: ['title', 'brand-abuse', 'competitor'],
    is_default: false,
    usage_count: 8,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },

  // ============================================
  // V10: Variation Abuse (8 templates)
  // Category: listing_content
  // ============================================
  {
    id: 'tmpl-v10-001',
    title: 'Variation Abuse — Unrelated Product Merged',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting variation policy abuse on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis listing has merged unrelated products into a single variation family to inherit reviews and ratings from the parent listing. The child ASINs in this variation are fundamentally different products that do not qualify as legitimate variations (e.g., different product types entirely).\n\nThis violates Amazon\'s Variation Relationship Policy which states variations must only differ in specific, related ways (size, color, style).\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'unrelated', 'merged'],
    is_default: true,
    usage_count: 40,
    created_by: 'demo-admin',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'tmpl-v10-002',
    title: 'Variation Abuse — Review Hijacking via Variation',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} is exploiting the variation system to hijack reviews.\n\nThe seller has added their product as a variation to a well-reviewed parent listing to benefit from existing positive reviews. The added product is not a legitimate variation of the parent product.\n\nCurrent rating: {{RATING}} with {{REVIEW_COUNT}} reviews (inherited, not earned).\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'review-hijack', 'reviews'],
    is_default: false,
    usage_count: 33,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-25T00:00:00Z',
  },
  {
    id: 'tmpl-v10-003',
    title: 'Variation Abuse — Size/Color Mismatch',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} has incorrect variation attributes.\n\nThe listed size or color variation does not match the actual product. The seller uses misleading variation labels (e.g., listing a completely different product as a "color" variant) to circumvent listing creation restrictions.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'size', 'color', 'mismatch'],
    is_default: false,
    usage_count: 26,
    created_by: 'demo-admin',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-02-22T00:00:00Z',
  },
  {
    id: 'tmpl-v10-004',
    title: 'Variation Abuse — Cross-Category Variation',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} violates variation policies by combining products from different categories.\n\nThe variation family includes items from different product categories or browse nodes, which is not permitted under Amazon\'s variation guidelines.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'cross-category'],
    is_default: false,
    usage_count: 18,
    created_by: 'demo-admin',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v10-005',
    title: 'Variation Abuse — Duplicate ASIN Variation',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} has duplicate variations.\n\nThe listing contains multiple variations that represent the same product, creating artificial listing inflation and confusing consumers.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'duplicate'],
    is_default: false,
    usage_count: 12,
    created_by: 'demo-admin',
    created_at: '2026-01-18T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'tmpl-v10-006',
    title: 'Variation Abuse — Accessory as Main Product Variant',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} has accessories listed as product variations.\n\nThe seller has added accessories or complementary products as variations of a main product. These are separate products that should have their own listings.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'accessory'],
    is_default: false,
    usage_count: 9,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'tmpl-v10-007',
    title: 'Variation Abuse — Brand Mixing in Variations',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} mixes brands within a variation family.\n\nThe variation listing includes products from different brands. This violates Amazon\'s policy that all variations must be from the same brand and product line.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'brand-mixing'],
    is_default: false,
    usage_count: 6,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-08T00:00:00Z',
  },
  {
    id: 'tmpl-v10-008',
    title: 'Variation Abuse — Price Manipulation via Variant',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} uses variation pricing manipulation.\n\nThe seller has created variations with artificially low prices (as low as {{PRICE}}) to appear in "lowest price" filters while the actual product is priced much higher. This bait-and-switch technique misleads consumers.\n\nDate: {{TODAY}}',
    category: 'listing_content',
    violation_types: ['V10'],
    marketplace: [],
    tags: ['variation', 'price', 'manipulation'],
    is_default: false,
    usage_count: 4,
    created_by: 'demo-admin',
    created_at: '2026-01-25T00:00:00Z',
    updated_at: '2026-02-05T00:00:00Z',
  },

  // ============================================
  // V11: Review Manipulation (5 templates)
  // Category: review_manipulation
  // ============================================
  {
    id: 'tmpl-v11-001',
    title: 'Review Manipulation — Incentivized Reviews',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting review manipulation on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThere is evidence that this listing has received incentivized reviews in exchange for free products, discounts, or other compensation. Patterns indicate:\n- Sudden spike in positive reviews over a short period\n- Multiple reviews from accounts with similar review patterns\n- Reviews that appear scripted or formulaic\n\nCurrent rating: {{RATING}} with {{REVIEW_COUNT}} reviews.\n\nThis violates Amazon\'s Community Guidelines which prohibit compensation for reviews.\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V11'],
    marketplace: [],
    tags: ['review', 'incentivized', 'fake'],
    is_default: true,
    usage_count: 52,
    created_by: 'demo-admin',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'tmpl-v11-002',
    title: 'Review Manipulation — Fake Negative Reviews on Competitor',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting fake negative reviews being posted on our Spigen product ASIN {{ASIN}} ("{{TITLE}}").\n\nWe have identified suspicious negative reviews that appear to be coordinated efforts to damage our product rating. These reviews contain false claims, are posted by accounts with patterns of reviewing competing products positively, and appear around the same time period.\n\nCurrent rating: {{RATING}} with {{REVIEW_COUNT}} reviews.\n\nWe believe a competitor ({{SELLER}}) is engaging in this practice.\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V11'],
    marketplace: [],
    tags: ['review', 'fake-negative', 'sabotage'],
    is_default: false,
    usage_count: 35,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-25T00:00:00Z',
  },
  {
    id: 'tmpl-v11-003',
    title: 'Review Manipulation — Review Farm Activity',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} shows evidence of review farm activity.\n\nMultiple reviews exhibit characteristics of review farm operations:\n- Reviewer accounts created within a short timeframe\n- Reviewers have reviewed many products from the same seller\n- Similar language and rating patterns across reviews\n- Verified purchase reviews followed by immediate returns\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V11'],
    marketplace: [],
    tags: ['review', 'farm', 'coordinated'],
    is_default: false,
    usage_count: 23,
    created_by: 'demo-admin',
    created_at: '2026-01-13T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v11-004',
    title: 'Review Manipulation — Insert Card Solicitation',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} includes product insert cards that solicit reviews.\n\nCustomer reports indicate the product includes packaging inserts offering incentives (discounts, free products, gift cards) in exchange for positive reviews. This violates Amazon\'s Community Guidelines and Seller Code of Conduct.\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V11'],
    marketplace: [],
    tags: ['review', 'insert-card', 'solicitation'],
    is_default: false,
    usage_count: 17,
    created_by: 'demo-admin',
    created_at: '2026-01-16T00:00:00Z',
    updated_at: '2026-02-16T00:00:00Z',
  },
  {
    id: 'tmpl-v11-005',
    title: 'Review Manipulation — Seller Self-Review',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} has reviews suspected to be from the seller or affiliates.\n\nReview analysis indicates several positive reviews appear to come from accounts linked to the seller or their associates, violating Amazon\'s prohibition on self-reviews and reviews from parties with a financial interest.\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V11'],
    marketplace: [],
    tags: ['review', 'self-review', 'seller'],
    is_default: false,
    usage_count: 10,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },

  // ============================================
  // V12: Review Hijacking (3 templates)
  // Category: review_manipulation
  // ============================================
  {
    id: 'tmpl-v12-001',
    title: 'Review Hijacking — Product Swap',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting review hijacking on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis listing has undergone a product swap — the original product that accumulated reviews has been replaced with a completely different product, while retaining the original reviews. This deceives consumers who rely on reviews to make purchase decisions.\n\nThe current product does not match the majority of reviews, as evidenced by older reviews describing a different product entirely.\n\nCurrent rating: {{RATING}} with {{REVIEW_COUNT}} reviews.\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V12'],
    marketplace: [],
    tags: ['review-hijack', 'product-swap', 'standard'],
    is_default: true,
    usage_count: 30,
    created_by: 'demo-admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-02-25T00:00:00Z',
  },
  {
    id: 'tmpl-v12-002',
    title: 'Review Hijacking — Listing Takeover',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} appears to have been hijacked.\n\nThe listing details (title, images, description) have been modified to represent a different product than originally listed, while the reviews from the original product remain. This is a common listing hijacking tactic.\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V12'],
    marketplace: [],
    tags: ['review-hijack', 'listing-takeover'],
    is_default: false,
    usage_count: 18,
    created_by: 'demo-admin',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v12-003',
    title: 'Review Hijacking — ASIN Merge Abuse',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} has been created through abusive ASIN merging.\n\nThe seller has merged multiple ASINs to consolidate reviews into a single listing, resulting in reviews for products that are no longer available or are different from the current offering. This inflates the review count and rating artificially.\n\nDate: {{TODAY}}',
    category: 'review_manipulation',
    violation_types: ['V12'],
    marketplace: [],
    tags: ['review-hijack', 'asin-merge'],
    is_default: false,
    usage_count: 11,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },

  // ============================================
  // V13: Price Manipulation (2 templates)
  // Category: selling_practice
  // ============================================
  {
    id: 'tmpl-v13-001',
    title: 'Price Manipulation — Artificial Price Inflation',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting price manipulation on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe seller is engaging in price manipulation by artificially inflating the "list price" or "was price" to create a misleading discount impression. The claimed original price has never been the actual selling price, making the displayed discount deceptive.\n\nCurrent price: {{PRICE}}.\n\nThis violates Amazon\'s Pricing Policy and Reference Price Guidelines.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V13'],
    marketplace: [],
    tags: ['price', 'inflation', 'fake-discount'],
    is_default: true,
    usage_count: 14,
    created_by: 'demo-admin',
    created_at: '2026-01-14T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v13-002',
    title: 'Price Manipulation — Bait-and-Switch Pricing',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} engages in bait-and-switch pricing.\n\nThe seller advertises a low price to attract clicks but the actual purchasable product (often the correct size/color) is priced significantly higher. This pricing practice misleads consumers.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V13'],
    marketplace: [],
    tags: ['price', 'bait-switch'],
    is_default: false,
    usage_count: 8,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },

  // ============================================
  // V14: Unauthorized Reseller (3 templates)
  // Category: selling_practice
  // ============================================
  {
    id: 'tmpl-v14-001',
    title: 'Unauthorized Reseller — Non-Authorized Spigen Seller',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting that {{SELLER}} on Amazon {{MARKETPLACE}} is selling Spigen products (ASIN {{ASIN}}, "{{TITLE}}") without authorization.\n\nSpigen Inc. maintains a selective distribution network and {{SELLER}} is not an authorized reseller. Products sold by unauthorized sellers may be:\n- Sourced from unauthorized channels\n- Outside of warranty coverage\n- Potentially defective or damaged units\n\nWe request investigation of this unauthorized seller\'s supply chain.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V14'],
    marketplace: [],
    tags: ['unauthorized', 'reseller', 'distribution'],
    is_default: true,
    usage_count: 20,
    created_by: 'demo-admin',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-02-22T00:00:00Z',
  },
  {
    id: 'tmpl-v14-002',
    title: 'Unauthorized Reseller — Grey Market Goods',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} appears to be selling grey market Spigen products.\n\nThe products appear to be imported from a different region (likely different packaging, warranty terms) and sold outside the authorized distribution channel. These goods may not meet the specifications or safety standards for this marketplace.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V14'],
    marketplace: [],
    tags: ['unauthorized', 'grey-market', 'import'],
    is_default: false,
    usage_count: 12,
    created_by: 'demo-admin',
    created_at: '2026-01-18T00:00:00Z',
    updated_at: '2026-02-16T00:00:00Z',
  },
  {
    id: 'tmpl-v14-003',
    title: 'Unauthorized Reseller — MAP Violation',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} is priced below our Minimum Advertised Price (MAP) at {{PRICE}}.\n\nThis pricing violates our MAP policy and suggests the seller is either unauthorized or sourcing through unapproved channels. Sub-MAP pricing damages our brand equity and authorized seller relationships.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V14'],
    marketplace: [],
    tags: ['unauthorized', 'map-violation', 'pricing'],
    is_default: false,
    usage_count: 9,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-12T00:00:00Z',
  },

  // ============================================
  // V15: Listing Hijacking / Bundling Violation (5 templates)
  // Category: selling_practice
  // ============================================
  {
    id: 'tmpl-v15-001',
    title: 'Listing Hijacking — Buy Box Takeover',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting listing hijacking on ASIN {{ASIN}} ("{{TITLE}}") on Amazon {{MARKETPLACE}}.\n\n{{SELLER}} has attached their offer to our Spigen listing without authorization. This seller is not an authorized Spigen reseller and may be selling counterfeit or unauthorized products under our listing. This hijacks our legitimate listing and can result in customers receiving non-genuine products.\n\nWe request that the unauthorized seller offer be removed from this ASIN.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V15'],
    marketplace: [],
    tags: ['hijacking', 'buy-box', 'standard'],
    is_default: true,
    usage_count: 45,
    created_by: 'demo-admin',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'tmpl-v15-002',
    title: 'Listing Hijacking — Detail Page Modification',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") on Amazon {{MARKETPLACE}} has had its detail page modified by unauthorized seller {{SELLER}}.\n\nThe listing title, images, or description have been altered to represent the hijacker\'s product rather than the original Spigen product. This is a serious violation that confuses consumers and harms our brand.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V15'],
    marketplace: [],
    tags: ['hijacking', 'detail-page', 'modification'],
    is_default: false,
    usage_count: 28,
    created_by: 'demo-admin',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-02-22T00:00:00Z',
  },
  {
    id: 'tmpl-v15-003',
    title: 'Listing Hijacking — Unauthorized Bundling',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} creates an unauthorized bundle with Spigen products.\n\nThe seller has created a listing that bundles a Spigen product with non-Spigen items without authorization. This misrepresents the product offering and can lead to customer confusion.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V15'],
    marketplace: [],
    tags: ['hijacking', 'bundle', 'unauthorized'],
    is_default: false,
    usage_count: 15,
    created_by: 'demo-admin',
    created_at: '2026-01-16T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v15-004',
    title: 'Listing Hijacking — Duplicate Listing Creation',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting a duplicate listing at ASIN {{ASIN}} ("{{TITLE}}") created by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis listing is a duplicate of an existing Spigen ASIN. The seller has created a separate listing for the same product to avoid competing on the original listing. This violates Amazon\'s policy against duplicate listings.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V15'],
    marketplace: [],
    tags: ['hijacking', 'duplicate', 'listing'],
    is_default: false,
    usage_count: 10,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },
  {
    id: 'tmpl-v15-005',
    title: 'Listing Hijacking — Condition Misrepresentation',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") has an offer from {{SELLER}} on Amazon {{MARKETPLACE}} that misrepresents product condition.\n\nThe seller is listing a used/refurbished product as "New" on our Spigen listing. Customer feedback confirms receiving products in opened/damaged packaging or showing signs of prior use.\n\nDate: {{TODAY}}',
    category: 'selling_practice',
    violation_types: ['V15'],
    marketplace: [],
    tags: ['hijacking', 'condition', 'used-as-new'],
    is_default: false,
    usage_count: 7,
    created_by: 'demo-admin',
    created_at: '2026-01-24T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },

  // ============================================
  // V16: Missing Certification (2 templates)
  // Category: regulatory_safety
  // ============================================
  {
    id: 'tmpl-v16-001',
    title: 'Missing Certification — FCC/UL Compliance',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting a regulatory compliance issue on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis electronic product/accessory appears to lack required FCC or UL certifications. Electronic products sold in the US must comply with FCC regulations, and products with electrical components require appropriate safety certifications.\n\nThe absence of these certifications indicates the product may not meet safety standards and poses potential risk to consumers.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V16'],
    marketplace: [],
    tags: ['certification', 'fcc', 'ul', 'compliance'],
    is_default: true,
    usage_count: 15,
    created_by: 'demo-admin',
    created_at: '2026-01-14T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v16-002',
    title: 'Missing Certification — CE/RoHS for EU Market',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} lacks required CE marking and RoHS compliance for the EU market.\n\nProducts sold in the European market must have CE marking and comply with RoHS directive for electronic products. The listing does not indicate compliance with these mandatory requirements.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V16'],
    marketplace: ['UK', 'DE', 'FR', 'IT', 'ES'],
    tags: ['certification', 'ce', 'rohs', 'eu'],
    is_default: false,
    usage_count: 8,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },

  // ============================================
  // V17: Safety Standards Violation (3 templates)
  // Category: regulatory_safety
  // ============================================
  {
    id: 'tmpl-v17-001',
    title: 'Safety Violation — Restricted Category Product',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting a safety concern with ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThis product appears to belong to a restricted product category that requires pre-approval for sale on Amazon. The seller may not have obtained the necessary approvals, and the product may not meet the safety requirements for this category.\n\nProducts in restricted categories must meet specific safety and quality standards to protect consumers.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V17'],
    marketplace: [],
    tags: ['safety', 'restricted', 'category'],
    is_default: true,
    usage_count: 11,
    created_by: 'demo-admin',
    created_at: '2026-01-12T00:00:00Z',
    updated_at: '2026-02-22T00:00:00Z',
  },
  {
    id: 'tmpl-v17-002',
    title: 'Safety Violation — Hazardous Material',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} may contain hazardous materials that are not properly disclosed.\n\nThe product appears to contain materials that require special handling, labeling, or certification. The listing does not include the required hazardous material warnings or safety data.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V17'],
    marketplace: [],
    tags: ['safety', 'hazardous', 'material'],
    is_default: false,
    usage_count: 6,
    created_by: 'demo-admin',
    created_at: '2026-01-18T00:00:00Z',
    updated_at: '2026-02-16T00:00:00Z',
  },
  {
    id: 'tmpl-v17-003',
    title: 'Safety Violation — Product Recall',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} appears to be a product that has been recalled or is subject to safety warnings.\n\nThe product matches descriptions of recalled items and should not be available for sale until the safety issue has been resolved by the manufacturer.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V17'],
    marketplace: [],
    tags: ['safety', 'recall'],
    is_default: false,
    usage_count: 3,
    created_by: 'demo-admin',
    created_at: '2026-01-24T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },

  // ============================================
  // V18: Missing Required Warnings (3 templates)
  // Category: regulatory_safety
  // ============================================
  {
    id: 'tmpl-v18-001',
    title: 'Missing Warnings — Prop 65 Warning',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting that ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} is missing required Proposition 65 warnings.\n\nProducts sold in California that contain chemicals listed under Proposition 65 must include appropriate warning labels. This listing does not display the required warnings, which is a violation of both Amazon\'s policies and California state law.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V18'],
    marketplace: ['US'],
    tags: ['warning', 'prop65', 'california'],
    is_default: true,
    usage_count: 9,
    created_by: 'demo-admin',
    created_at: '2026-01-14T00:00:00Z',
    updated_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'tmpl-v18-002',
    title: 'Missing Warnings — Choking Hazard / Age Warning',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} is missing required age/choking hazard warnings.\n\nProducts with small parts that could be a choking hazard for children must include appropriate warnings per CPSIA requirements. This listing does not display these mandatory safety warnings.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V18'],
    marketplace: [],
    tags: ['warning', 'choking', 'children'],
    is_default: false,
    usage_count: 5,
    created_by: 'demo-admin',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },
  {
    id: 'tmpl-v18-003',
    title: 'Missing Warnings — Battery Safety Warning',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} contains batteries but lacks required safety warnings.\n\nProducts containing lithium batteries or other battery types must include proper safety warnings and handling instructions as required by DOT and Amazon\'s Dangerous Goods program.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V18'],
    marketplace: [],
    tags: ['warning', 'battery', 'lithium'],
    is_default: false,
    usage_count: 4,
    created_by: 'demo-admin',
    created_at: '2026-01-24T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },

  // ============================================
  // V19: Import Regulation Violation (2 templates)
  // Category: regulatory_safety
  // ============================================
  {
    id: 'tmpl-v19-001',
    title: 'Import Violation — Missing Country of Origin',
    body: 'Dear Amazon Seller Performance Team,\n\nI am reporting an import regulation violation on ASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}}.\n\nThe product listing does not display the required country of origin information. US Customs and Border Protection requires that all imported products clearly indicate their country of manufacture. The absence of this information suggests the product may not comply with import regulations.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V19'],
    marketplace: ['US'],
    tags: ['import', 'country-of-origin', 'customs'],
    is_default: true,
    usage_count: 7,
    created_by: 'demo-admin',
    created_at: '2026-01-16T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'tmpl-v19-002',
    title: 'Import Violation — Suspected Tariff Evasion',
    body: 'Dear Amazon Seller Performance Team,\n\nASIN {{ASIN}} ("{{TITLE}}") sold by {{SELLER}} on Amazon {{MARKETPLACE}} at {{PRICE}} may be involved in tariff evasion.\n\nThe extremely low pricing combined with product characteristics suggest the seller may be circumventing import tariffs or duties. The pricing is below what would be commercially viable with proper tariff compliance.\n\nDate: {{TODAY}}',
    category: 'regulatory_safety',
    violation_types: ['V19'],
    marketplace: [],
    tags: ['import', 'tariff', 'evasion'],
    is_default: false,
    usage_count: 3,
    created_by: 'demo-admin',
    created_at: '2026-01-22T00:00:00Z',
    updated_at: '2026-02-14T00:00:00Z',
  },
]
